# Generated by Django 2.2.2 on 2019-06-07 15:57

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', imagekit.models.fields.ProcessedImageField(default='', upload_to='icon', verbose_name='球队图标')),
                ('name', models.CharField(max_length=50, verbose_name='球队名称')),
                ('rank', models.IntegerField(verbose_name='球队排名')),
                ('score', models.IntegerField(verbose_name='球队积分')),
                ('create_date', models.DateField(verbose_name='创建年份')),
                ('city', models.CharField(max_length=50, verbose_name='球队城市')),
                ('coach', models.CharField(max_length=50, verbose_name='主帅')),
                ('star', models.CharField(max_length=150, verbose_name='球星')),
                ('description', models.CharField(default='', max_length=500, verbose_name='球队介绍')),
                ('slug', models.SlugField(default='唯一值', unique=True, verbose_name='球队标识')),
            ],
            options={
                'verbose_name': '球队',
                'verbose_name_plural': '球队',
                'ordering': ['-score'],
            },
        ),
    ]
